export { Hero } from './components/Hero'
export { Header } from './components/Header'
export { CustomCursor } from './components/CustomCursor'
export { FundadorasStrip } from './components/FundadorasStrip'
export { Manifesto } from './components/Manifesto'
export { ManualSection } from './components/ManualSection'
export { ManuaisSection as FasesCuidado } from './components/ManuaisSection'
export { ManuaisSection } from './components/ManuaisSection'
export { Consultoria } from './components/Consultoria'
export { PorQuemViveu } from './components/PorQuemViveu'
export { Conteudo } from './components/Conteudo'
export { CTAFinal } from './components/CTAFinal'
export { Footer } from './components/Footer'
export { WhatsAppFloat } from './components/WhatsAppFloat'
export { SplashScreen } from './components/SplashScreen'
